[package]
name = "fastx"
version = "0.1.0"
authors = ["Moold <mooldhu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = { version = ">=0.2.18", features = ["zlib"], default-features = false }