[package]
name = "fastx"
version = "0.1.0"
authors = ["Moold <mooldhu@gmail.com>"]
edition = "2018"
license = "MIT"
description = "a simple fasta/fastq (fastx) format parser library"
homepage = "https://github.com/moold/fastx"
repository = "https://github.com/moold/fastx"
readme = "README.md"
keywords  = ["fastq", "fasta"]

[dependencies]
flate2 = { version = ">=0.2.18", features = ["zlib"], default-features = false }
